import Card from "@/components/Card";
import Head from "next/head";

interface HomeProps {
  data: any;
}

export default function Home({ data }: HomeProps) {
  return (
    <>
      <Head>
        <title>Movie List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-screen-lg m-auto grid gap-5 grid-cols-2 sm:grid-cols-3 xl:grid-cols-4 p-4 lg:p-8">
        {data.map((item: any) => (
          <Card movie={item} key={item.show.id} />
        ))}
      </main>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch("http://api.tvmaze.com/search/shows?q=girls");
  const data = await res.json();

  return {
    props: { data },
  };
}
